version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - app-network

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
# volumes:
#   model_volume:
